version: "3.8"
services:
  backend:
    image: ddadadadaddada/llm-based-chatbot-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env

  streamlit:
    image: ddadadadaddada/llm-based-chatbot-streamlit:latest
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - backend
